#define FAN_IOCTL_START_NUM 0x80
#define FAN_IOCTL_NUM1 FAN_IOCTL_START_NUM+1
#define FAN_IOCTL_NUM2 FAN_IOCTL_START_NUM+2

#define FAN_IOCTL_NUM 'z'
#define FAN_ACTIVE _IOWR(FAN_IOCTL_NUM, FAN_IOCTL_NUM1, unsigned long)
#define DHT11_GET _IOWR(FAN_IOCTL_NUM, FAN_IOCTL_NUM2, unsigned long)
